export const SPORTS = [
  { id: '-1', icon: '', name: 'All sports', color: 'bbb'},
  { id: '0', icon: 'directions-run', name: 'Running', color: '0bb' },
  { id: '1', icon: 'directions-bike', name: 'Cycling (Transport)', color: 'b0b' },
  { id: '2', icon: 'directions-bike', name: 'Cycling (Sport)', color: 'bb0' },
  { id: '3', name: 'Mountain biking' },
  { id: '4', name: 'Roller skating' },
  { id: '5', icon: 'airline-seat-legroom-normal', name: 'Roller skiing', color: 'b00' },
  { id: '6', name: 'Skiing (Cross country)' },
  { id: '7', name: 'Skiing (Downhill)' },
  { id: '8', name: 'Snowboarding' },
  { id: '9', name: 'Kayaking' },
  { id: '10', name: 'Kite surfing' },
  { id: '11', name: 'Rowing' },
  { id: '12', name: 'Sailing' },
  { id: '13', name: 'Windsurfing' },
  { id: '14', name: 'Walking (Fitness)' },
  { id: '15', name: 'Golfing' },
  { id: '16', name: 'Hiking' },
  { id: '17', name: 'Orienteering' },
  { id: '18', icon: 'directions-walk', name: 'Walking', color: '00b' },
  { id: '19', name: 'Riding' },
  { id: '20', name: 'Swimming' },
  { id: '21', name: 'Cycling (Indoor)' },
  { id: '22', name: 'Other' },
  { id: '23', name: 'Aerobics' },
  { id: '24', name: 'Badminton' },
  { id: '25', name: 'Baseball' },
  { id: '26', name: 'Basketball' },
  { id: '27', name: 'Boxing' },
  { id: '28', name: 'Climbing stairs' },
  { id: '29', name: 'Cricket' },
  { id: '30', name: 'Elliptical training' },
  { id: '31', name: 'Dancing' },
  { id: '32', name: 'Fencing' },
  { id: '33', name: 'Football (American)' },
  { id: '34', name: 'Football (Rugby)' },
  { id: '35', name: 'Football (Soccer)' },
  { id: '36', name: 'Handball' },
  { id: '37', name: 'Hockey' },
  { id: '38', name: 'Pilates' },
  { id: '39', name: 'Polo' },
  { id: '40', name: 'Scuba diving' },
  { id: '41', name: 'Squash' },
  { id: '42', name: 'Table tennis' },
  { id: '43', name: 'Tennis' },
  { id: '44', name: 'Volleyball (Beach)' },
  { id: '45', name: 'Volleyball (Indoor)' },
  { id: '46', name: 'Weight training' },
  { id: '47', name: 'Yoga' },
  { id: '48', name: 'Martial arts' },
  { id: '49', name: 'Gymnastics' },
  { id: '50', name: 'Step counter' },
  { id: '87', name: 'Circuit Training' },
  { id: '88', name: 'Running (Treadmill)' },
  { id: '89', name: 'Skateboarding' },
  { id: '90', name: 'Surfing' },
  { id: '91', name: 'Snowshoeing' },
  { id: '92', name: 'Wheelchair' },
  { id: '93', name: 'Climbing' },
  { id: '94', name: 'Walking (Treadmill)' },
  { id: '95', icon: 'pets', name: 'Kick scooter', color: '0b0' },
  { id: '96', name: 'Stand Up Paddling' },
  { id: '97', name: 'Trail Running' },
  { id: '98', name: 'Rowing (indoors)' },
  { id: '99', name: 'Floorball' },
  { id: '100', name: 'Ice skating' },
  { id: '101', name: 'Ski Touring' },
  { id: '102', name: 'Rope jumping' },
  { id: '103', name: 'Stretching' },
  { id: '104', name: 'Canicross' },
  { id: '105', name: 'Paddle tennis' },
  { id: '106', name: 'Paragliding' }
];
